### ISSUE TITLE
App is not showing in all applications

### ISSUE THREAD

**Issue by NayanaRBhoj** [ccgcool/Wallpaperchanger#1]
Application is not installed does not show in all apps.

**Comment by ccgcool** [comment]
Thank You. It's currently designed to work as a service. You can share images from other apps like Facebook and it'll add it to Your list of images which it'll keep changing. It's not designed to launch from launcher like general apps. Sorry for that. I'm still working on it.

**Comment by NayanaRBhoj** [comment]
I also want the same scenario in my app that is, use will select few
picture from gallery nd only those wallpapers will be shown on lockscreen
every time new pic.

**Comment by ccgcool** [comment]
Ok. If You want to share many images from gallery in one shot, then I guess related intent filtering and handling is needed. I've not thought of this idea, hence haven't worked on this requirement.
